CREATE DATABASE CREDENTIALS_MANAGER;

USE CREDENTIALS_MANAGER;

CREATE TABLE users(
	id INT NOT NULL AUTO_INCREMENT,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE credentials(
	id INT NOT NULL AUTO_INCREMENT,
    user_id INT,
    app VARCHAR(225) NOT NULL,
    email VARCHAR(255) NOT NULL,
    username VARCHAR(255),
    password VARCHAR(255) NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id)
);